spring:
  application:
    name: "bee-admin"
  datasource:
    url: "jdbc:mysql://localhost/bee"
    username: "root"
    password: "123456"
server:
  port: 11000
  servlet:
    context-path: "/bee-admin"

## 这个配置是优先log4j2.xml的
logging:
  level:
    root: info

### 这个配置打印mybatis的日志
mybatis-plus:
#  mapper-locations: classpath*:mapper/*Mapper.xml
  #  type-aliases-package: com.github
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

